const LEGAL_PATHS = ["/privacy", "/terms", "/delivery", "/payment", "/returns", "/contacts", "/legal"];
const REQUIRED_ENV = ["LEGAL_BUSINESS_NAME", "LEGAL_ENTITY_FORM", "LEGAL_REGISTRATION_ID", "LEGAL_TAX_ID", "LEGAL_ADDRESS", "LEGAL_POSTAL_ADDRESS", "PUBLIC_PHONE", "PUBLIC_EMAIL", "PUBLIC_WORKING_HOURS", "LEGAL_JURISDICTION", "LEGAL_PROCESSORS", "LEGAL_EFFECTIVE_DATE", "PRIVACY_POLICY_VERSION", "TERMS_VERSION", "CUSTOMER_DATA_RETENTION", "ORDER_DATA_RETENTION", "LOG_RETENTION", "BACKUP_RETENTION", "ORDER_CONFIRMATION_TERMS", "DELIVERY_TERRITORY", "DELIVERY_METHODS", "PICKUP_TERMS", "DELIVERY_COST_TERMS", "DELIVERY_TIME_TERMS", "DELIVERY_CHANGE_TERMS", "UNLOADING_TERMS", "OVERSIZE_TERMS", "PAYMENT_METHODS_PUBLIC", "PAYMENT_TIMING", "PAYMENT_DOCUMENTS", "CASHLESS_TERMS", "REFUND_PROCESS", "PUBLIC_CURRENCY", "RETURN_CATEGORIES", "RETURN_PERIOD_TERMS", "RETURN_CONDITION", "RETURN_REQUEST_PROCESS", "RETURN_DOCUMENTS", "RETURN_SHIPPING", "RETURN_EXCEPTIONS", "REFUND_TIME", "LIABILITY_TERMS", "FORCE_MAJEURE_TERMS"];
const placeholders = {
    business: "[ПОЛНОЕ НАИМЕНОВАНИЕ ПРОДАВЦА]", form: "[ОРГАНИЗАЦИОННО-ПРАВОВАЯ ФОРМА]", registration: "[РЕГИСТРАЦИОННЫЙ НОМЕР / ИНН]", address: "[ЮРИДИЧЕСКИЙ АДРЕС]", postal: "[ПОЧТОВЫЙ АДРЕС]", email: "[EMAIL]", phone: "[ТЕЛЕФОН]", jurisdiction: "[СТРАНА И ПРИМЕНИМОЕ ПРАВО]", retention: "[СРОК ХРАНЕНИЯ ДАННЫХ]", returns: "[СРОК И УСЛОВИЯ ВОЗВРАТА]", delivery: "[СПОСОБЫ ДОСТАВКИ]", payment: "[СПОСОБЫ ОПЛАТЫ]", processors: "[НАЗВАНИЯ СТОРОННИХ СЕРВИСОВ]" };

function legalConfig(env = process.env) {
    const value = (name, placeholder) => String(env[name] || placeholder || "").trim();
    return {
        businessName: value("LEGAL_BUSINESS_NAME", placeholders.business), entityForm: value("LEGAL_ENTITY_FORM", placeholders.form), registrationId: value("LEGAL_REGISTRATION_ID", placeholders.registration), taxId: value("LEGAL_TAX_ID", placeholders.registration), address: value("LEGAL_ADDRESS", placeholders.address), postalAddress: value("LEGAL_POSTAL_ADDRESS", placeholders.postal), phone: value("PUBLIC_PHONE", placeholders.phone), email: value("PUBLIC_EMAIL", placeholders.email), workingHours: value("PUBLIC_WORKING_HOURS", "[РЕЖИМ РАБОТЫ]"), jurisdiction: value("LEGAL_JURISDICTION", placeholders.jurisdiction), processors: value("LEGAL_PROCESSORS", placeholders.processors), effectiveDate: value("LEGAL_EFFECTIVE_DATE", "[ДАТА ВСТУПЛЕНИЯ В СИЛУ]"),
        privacyVersion: value("PRIVACY_POLICY_VERSION", "DRAFT"), termsVersion: value("TERMS_VERSION", "DRAFT"), customerRetention: value("CUSTOMER_DATA_RETENTION", placeholders.retention), orderRetention: value("ORDER_DATA_RETENTION", placeholders.retention), logRetention: value("LOG_RETENTION", placeholders.retention), backupRetention: value("BACKUP_RETENTION", placeholders.retention),
        orderConfirmation: value("ORDER_CONFIRMATION_TERMS", "[ПОРЯДОК ПОДТВЕРЖДЕНИЯ ЗАКАЗА]"), deliveryTerritory: value("DELIVERY_TERRITORY", "[ТЕРРИТОРИЯ ДОСТАВКИ]"), deliveryMethods: value("DELIVERY_METHODS", placeholders.delivery), pickup: value("PICKUP_TERMS", "[УСЛОВИЯ САМОВЫВОЗА]"), deliveryCost: value("DELIVERY_COST_TERMS", "[СТОИМОСТЬ ДОСТАВКИ]"), deliveryTime: value("DELIVERY_TIME_TERMS", "[СРОКИ ДОСТАВКИ]"), deliveryChange: value("DELIVERY_CHANGE_TERMS", "[ПОРЯДОК ИЗМЕНЕНИЯ СРОКОВ]"), unloading: value("UNLOADING_TERMS", "[УСЛОВИЯ РАЗГРУЗКИ]"), oversize: value("OVERSIZE_TERMS", "[КРУПНОГАБАРИТНЫЕ ТОВАРЫ]"), paymentMethods: value("PAYMENT_METHODS_PUBLIC", placeholders.payment), paymentTiming: value("PAYMENT_TIMING", "[МОМЕНТ ОПЛАТЫ]"), paymentDocuments: value("PAYMENT_DOCUMENTS", "[ПЛАТЁЖНЫЕ ДОКУМЕНТЫ]"), cashless: value("CASHLESS_TERMS", "[БЕЗНАЛИЧНЫЙ РАСЧЁТ]"), refundProcess: value("REFUND_PROCESS", "[ПОРЯДОК ВОЗВРАТА СРЕДСТВ]"), currency: value("PUBLIC_CURRENCY", "[ВАЛЮТА]"), returnCategories: value("RETURN_CATEGORIES", "[КАТЕГОРИИ ТОВАРОВ]"), returnPeriod: value("RETURN_PERIOD_TERMS", placeholders.returns), returnCondition: value("RETURN_CONDITION", "[СОСТОЯНИЕ ТОВАРА]"), returnRequest: value("RETURN_REQUEST_PROCESS", "[ПРОЦЕДУРА ОБРАЩЕНИЯ]"), returnDocuments: value("RETURN_DOCUMENTS", "[НЕОБХОДИМЫЕ ДОКУМЕНТЫ]"), returnShipping: value("RETURN_SHIPPING", "[ОБРАТНАЯ ДОСТАВКА]"), returnExceptions: value("RETURN_EXCEPTIONS", "[ИСКЛЮЧЕНИЯ]"), refundTime: value("REFUND_TIME", "[СРОК ВОЗВРАТА ДЕНЕГ]"), liability: value("LIABILITY_TERMS", "[ОТВЕТСТВЕННОСТЬ]"), forceMajeure: value("FORCE_MAJEURE_TERMS", "[ФОРС-МАЖОР]")
    };
}
function containsPlaceholder(value) { return /\[[^\]]+\]|\bDRAFT\b/i.test(String(value || "")); }
function readiness(env = process.env) {
    const config = legalConfig(env); const missing = REQUIRED_ENV.filter(name => !String(env[name] || "").trim());
    const invalid = []; if (env.PUBLIC_EMAIL && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(env.PUBLIC_EMAIL)) invalid.push("PUBLIC_EMAIL"); if (env.PUBLIC_PHONE && !/^\+?[0-9 ()-]{7,25}$/.test(env.PUBLIC_PHONE)) invalid.push("PUBLIC_PHONE");
    let canonicalBase = "";
    if (env.PUBLIC_BASE_URL) {
        try { const parsed = new URL(env.PUBLIC_BASE_URL); if (!["http:", "https:"].includes(parsed.protocol) || parsed.origin !== env.PUBLIC_BASE_URL.replace(/\/$/, "")) invalid.push("PUBLIC_BASE_URL"); else canonicalBase = parsed.origin; }
        catch { invalid.push("PUBLIC_BASE_URL"); }
    } else if (env.NODE_ENV === "production") invalid.push("PUBLIC_BASE_URL");
    const placeholderFields = Object.entries(config).filter(([, value]) => containsPlaceholder(value)).map(([name]) => name);
    const contentPlaceholders = [...JSON.stringify(documentDefinitions(config)).matchAll(/\[[А-ЯЁ][А-ЯЁA-Z0-9 _/.-]{2,}\]/g)].map(match => match[0]);
    return { ready: !missing.length && !invalid.length && !placeholderFields.length && !contentPlaceholders.length, missing, invalid, placeholderFields, contentPlaceholders, versions: { privacy: config.privacyVersion, terms: config.termsVersion }, canonicalBase };
}
function documentDefinitions(config) {
    const approval = "Шаблон требует проверки и утверждения владельцем проекта и юридическим специалистом для фактической юрисдикции и бизнес-модели.";
    return {
        "/privacy": { title: "Политика конфиденциальности", description: "Шаблон политики обработки персональных данных MatMix.", sections: [["Оператор", `${config.businessName}; ${config.address}; ${config.email}.`], ["Фактически собираемые данные", "Имя, телефон, выбранный способ связи, адрес доставки, сведения о разгрузке и оплате, комментарий, состав и стоимость заказа. Корзина и подсказки формы хранятся локально в браузере. CRM использует обязательную session-cookie; аналитические и рекламные cookies в проекте не обнаружены."], ["Цели и обязательность", "Имя и телефон обязательны для оформления заказа. Остальные поля используются в соответствии с интерфейсом заказа; правовое основание должно быть подтверждено владельцем."], ["Источники, получатели и обработчики", `Источник — пользовательская форма. Доступ имеют уполномоченные сотрудники CRM. Сторонние обработчики: ${config.processors}.`], ["Хранение и защита", `Срок хранения: ${config.customerRetention}; заказы: ${config.orderRetention}; журналы: ${config.logRetention}; backup: ${config.backupRetention}.`], ["Права и обращения", `Порядок запросов и применимое право: ${config.jurisdiction}. Обращения: ${config.email}.`], ["Cookies и локальное хранилище", "Корзина и ранее введённые подсказки используют localStorage и не являются cookies. Необязательные трекеры отсутствуют."], ["Изменения, версия и дата", `Версия: ${config.privacyVersion}. Дата вступления в силу: ${config.effectiveDate}.`]] },
        "/terms": { title: "Условия использования и продажи", description: "Шаблон условий оформления заказов MatMix.", sections: [["Продавец", `${config.businessName}; ${config.entityForm}; ${config.registrationId}; ${config.address}.`], ["Предмет, каталог и цены", "Каталог и цена фиксируются при серверной проверке заказа. Для товара без цены применяется согласуемая с менеджером цена по запросу."], ["Оформление и подтверждение", config.orderConfirmation], ["Оплата", `${config.paymentMethods}; ${config.paymentTiming}.`], ["Доставка и получение", `${config.deliveryMethods}; ${config.deliveryTime}.`], ["Возврат", `${config.returnPeriod}; ${config.returnRequest}.`], ["Ответственность и форс-мажор", `${config.liability}; ${config.forceMajeure}.`], ["Персональные данные", "Обработка описывается в политике конфиденциальности."], ["Изменение условий и право", `${config.jurisdiction}; версия ${config.termsVersion}; дата ${config.effectiveDate}.`], ["Контакты", `${config.phone}; ${config.email}.`]] },
        "/delivery": { title: "Доставка", description: "Шаблон условий доставки MatMix.", sections: [["Территория и способы", `${config.deliveryTerritory}; ${config.deliveryMethods}; ${config.pickup}.`], ["Стоимость и сроки", `${config.deliveryCost}; ${config.deliveryTime}; ${config.deliveryChange}.`], ["Разгрузка и крупногабаритные товары", `${config.unloading}; ${config.oversize}.`], ["Контакт", config.phone]] },
        "/payment": { title: "Оплата", description: "Шаблон условий оплаты MatMix.", sections: [["Способы и момент оплаты", `${config.paymentMethods}; ${config.paymentTiming}.`], ["Документы и безналичный расчёт", `${config.paymentDocuments}; ${config.cashless}.`], ["Возврат средств и валюта", `${config.refundProcess}; ${config.currency}.`]] },
        "/returns": { title: "Возврат товаров", description: "Шаблон условий возврата товаров MatMix.", sections: [["Категории, сроки и состояние", `${config.returnCategories}; ${config.returnPeriod}; ${config.returnCondition}.`], ["Порядок обращения", `${config.returnRequest}; ${config.returnDocuments}.`], ["Доставка, исключения и деньги", `${config.returnShipping}; ${config.returnExceptions}; ${config.refundTime}.`]] },
        "/contacts": { title: "Контакты и реквизиты", description: "Контактная и юридическая информация MatMix.", sections: [["Наименование", config.businessName], ["Регистрационные данные", `${config.registrationId}; ${config.taxId}.`], ["Адрес", config.address === config.postalAddress ? `${config.address}.` : `${config.address}; ${config.postalAddress}.`], ["Связь", `${config.phone}; ${config.email}; ${config.workingHours}.`]] },
        "/legal": { title: "Юридическая информация", description: "Юридические документы и реквизиты MatMix.", sections: [["Продавец", config.businessName], ["Юрисдикция", config.jurisdiction], ["Документы", "Политика конфиденциальности, условия продажи, доставка, оплата и возврат доступны по ссылкам ниже."]] }
    };
}
module.exports = { LEGAL_PATHS, REQUIRED_ENV, placeholders, legalConfig, containsPlaceholder, readiness, documentDefinitions };
